### ISSUE TITLE
create Env class to read safe environment variables

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/milk-sdk-php#19]
Instead of using getenv use $_ENV for reading environment varibles.
To to that , in a safe way , create Env class with getenv method

```php
public static function getenv($parameter, $default = "")
```

**Comment by tharindulucky** [comment]
@roberto-butti I'd like to work on this issue. So, what you are expeciting is to use environment variables like this right ?

```
Env::value('database);
```

**Comment by roberto-butti** [comment]
> @roberto-butti I'd like to work on this issue. So, what you are expeciting is to use environment variables like this right ?
> 
> ```
> Env::value('database);
> ```

Thank you!!!
I was thinking about it.
I'm going to provide more information:
- create file: src/Utils/Environment.php
- class name: class Environment

Specs:
```
    /**
     * get environment variable via $_ENV
     * If the parameter doesn't exist, it is returned $default
     * @param string $parameter
     * @param string $default
     * @return mixed|string
     */
    public static function getEnv(string $parameter, $default = "")
```

Usage example 
```
Environment::getEnv("XYZ_API_HOSTNAME", self::HOST_PROD);
```

**Comment by tharindulucky** [comment]
Thanks! I'll start developments!

**Comment by tharindulucky** [comment]
Is there a developers chat on Discord ? 
And btw, I'm getting  this error when installing to Laravel. Any idea why this is ?

![image](https://user-images.githubusercontent.com/15250118/96337137-5a42b680-10a2-11eb-9aea-f3d9d5eb034e.png)

**Comment by roberto-butti** [comment]
i'm going to open a new issues to solve.
Anyway you can use it without LAravel if for now this is ablocker for your test.
you can use one of those examples in example directory

**Comment by tharindulucky** [comment]
Great! Thanks!

**Comment by tharindulucky** [comment]
I added a PR #20 for this issue. Let me know what you think. Thanks!

**Comment by roberto-butti** [comment]
Thank you @tharindulucky . Great! I merged PR.
I think it is ok retrieve the parameter via _ENV , and also great use of Null coalescing operator

**Comment by tharindulucky** [comment]
Thanks a lot! Happy to contribute!
