### ISSUE TITLE
phpstan level 6

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/milk-sdk-php#28]
Update code in order to resolve all warnings provided by phpstan with level=6

**Comment by creativenull** [comment]
Hey! Can I try this?

**Comment by roberto-butti** [comment]
> Hey! Can I try this?

Sure @creativenull . thank you! I think this is a huge issue now we have 91 warnings in master branch on multiple files.
I think you could start on HiFolks\Milk\Utils\ classes and open a PR just for them.
What do you tihnk ?

**Comment by creativenull** [comment]
Ok, I was thinking of fixing all of the errors 😅. I can start on the one you requested if you want it to be done that way.

I did run the analyze and saw there were mostly typehinting errors, and since PHP 7 allows typehints in code, do you want me to use them and if it's a complex return type then use the typehints in comments? So a mixture of typehint in code and comments or typehint only inside comments?

What I mean:
```php
/**
 * I can add mixed here
 * @param string $code
 * @return mixed
 */
function check(string $code): mixed // BUT can't add mixed here
{
  if (...) {
    return true;
  } else {
    return "Perfect";
  }
}
```

**Comment by roberto-butti** [comment]
Hi, usually i add type hinting in the param phpcode **and** in the function parameter. Following your example:

```php
/**
 * I can add mixed here
 * @param string $code
 * @return mixed
 */
function check(string $code)
{
  if (...) {
    return true;
  } else {
    return "Perfect";
  }
}
```




or (if the parameter is not mandatory):
```php
/**
 * I can add mixed here
 * @param string $code
 * @return mixed
 */
function check($code = "")
{
  if (...) {
    return true;
  } else {
    return "Perfect";
  }
}
```

**Comment by creativenull** [comment]
Alright! So just work on the files inside `HiFolks\Milk\Utils` for now?

**Comment by roberto-butti** [comment]
> Alright! So just work on the files inside `HiFolks\Milk\Utils` for now?

This was my suggestion to avoid to abuse of your time ;)
If you have time and patience, you could fix all of these ;)
I any case , your effort is appreciated!

**Comment by creativenull** [comment]
I ended up fixing all the errors, please review the PR and let me know if any changes are required.

**Comment by roberto-butti** [comment]
This PR was perfect, thank you!!! Merged into _master_
