### ISSUE TITLE
Add phpcs to composer.json

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/milk-sdk-php#35]
Add the codesniffer package in __dev__ section.
In _composer.json_ , in _require-dev_ section, add squizlabs/php_codesniffer package:
```
{
    "require-dev": {
        "squizlabs/php_codesniffer": "3.*"
    }
}
```

So after that you can execute vendor/bin/phpcs.

**Comment by kimcheung** [comment]
Hi, can I also work on this?

**Comment by roberto-butti** [comment]
@kimcheung I merged your PR! thank you!
