### ISSUE TITLE
Add Map Image API usage documentation in Readme.md

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/milk-sdk-php#61]
In readme file, after "Isoline API" section and before "Useful reference" section add "Map Image API" to show some usage of MapImage class.
Use examples/20_map_image.php file to see some example of MapImage usage.

**Comment by soil-droid** [comment]
can i work on this?

**Comment by roberto-butti** [comment]
Sure, @soil-droid  , thank you!

**Comment by roberto-butti** [comment]
Thank you @soil-droid  I just merged your PR! thank you!
