### ISSUE TITLE
Improve documentation for Weather API in readme.md

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/milk-sdk-php#78]
In readme.md file, in Weather API section, add some information about Weather class methods like:
- productObservation()
- productAlerts()
- productForecast7days()
- productForecast7daysSimple()
- productForecastAstronomy()
- productForecastHourly()
- productNwsAlerts()

Considering these notes:
```
     * Set the product for the Weather API
     * A parameter identifying the type of report to obtain.
     * The possible values are as follows:
     * - observation – current weather conditions from the eight closest locations to the specified location
     * - forecast_7days – morning, afternoon, evening and night weather forecasts for the next seven days.
     * - forecast_7days_simple – daily weather forecasts for the next seven days
     * - forecast_hourly – hourly weather forecasts for the next seven days
     * - forecast_astronomy – information on when the sun and moon rise and set,
     * and on the phase of the moon for the next seven days
     * - alerts – forecasted weather alerts for the next 24 hours
     * - nws_alerts – all active watches and warnings for the US and Canada
```

**Comment by ckbball** [comment]
Do you have a style guideline?

**Comment by roberto-butti** [comment]
Hi @ckbball , I don't have a styleguide.
But you can follow as example https://github.com/Hi-Folks/milk-sdk-php#map-image-api Map Image Api  in the readme file, where I explained the goal of the class and I listed the most relevant methods with bullet point.
